### ISSUE TITLE
Register new and edit existing applications and versions

### ISSUE THREAD

**Issue by tovop** [SevanSSP/avm#4]
## Wishlist

I would like to be able to:

- Register new applications
- Register new versions to existing applications
- Edit existing applications and versions
- Change an application's default version

### General
Create xml reader that returns an object hierarchy ApplicationVersionRegister - Application (many) -Version (many).

## ApplicationVersionRegister
Attributes
- path
- applications

Methods
- new_application(applicationname)
- new_version(applicationname, …)
- update/refresh (pushing changes back to path/xmlfile)

### Application
Attributes
- name
- default_version (property, setter and getter?, check that version exists)

Methods
- new_version(...)

### Version
Attributes
- number
- installdir
- exefilepath
- platform
- usermanualpath
- platform
- producttype
- category
- helpfile
- userspecifieddefault (??)
- persistencetype (??)

**Comment by EBGlom** [comment]
This is managed through the DNV Software
